"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pymterm/pymterm.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
               'includes':['GUI.*',
                           'colour.*',
                           'cap.*',
                           'objc.*',
                           'cairo.*',
                           'pango.*',
                           'pkg_resources.*',
                           'pkg_resources._vendor.*',
                           'pkg_resources._vendor.packaging.*',
                           'pkg_resources.extern.*'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
